### PR TITLE
Support column in C0301: Line too long (%s/%s)

### PR DESCRIPTION
**Pull request by nfvs**

### CODE REVIEW

**Comment by NotSqrt** [comment]
Thanks !

**Comment by nfvs** [comment]
No problem. I'm already part of the SublimeLinter org but I don't have permissions for this repo; any chance of getting them?

**Comment by NotSqrt** [comment]
hum, that sounds like a consequence of the fact that I was the first creator of multiple linters, incorporated under the SublimeLinter org, with a specific team, by aparajita.

See https://github.com/orgs/SublimeLinter/teams/notsqrt-cppcheck-cpplint-pylint-pyyaml-shellcheck

**Comment by nfvs** [comment]
I don't have access to that, teams in this org are private; if you make me part of the pylint team I can have access as well.

**Comment by NotSqrt** [comment]
Except I'm just a member of that team, not a manager ..

**Pull request merged**
