### PR TITLE
cleanup deprecated stuff and simplify travis test

### PR DESCRIPTION
**Pull request by braver**

### CODE REVIEW

**Comment by braver** [comment]
I restored the defaults, but would need more time to refactor out the the `build_args`

**Comment by braver** [comment]
This is a bit too much for me to dig into right now. If anyone wants to pick it up be my guest.

**Comment by kaste** [comment]
SL > 4.3 required

I made a similar PR today (clang?) where it seems better if the default args DSL abracadabra would accept a callable. Here we implement `cmd()` although the actual `cmd` is somewhat static. We just use this extension point to manipulate the settings, here `init-hook`. The arg `init-hook` gets inserted by SL automatically after that. (So the benefit is we can claim `build_args` for SL core refactorings, and a plugin author should not mess with `args` manually but stay declarative.)

@braver?

**Comment by braver** [comment]
Ok, LGTM basically. 4.3 is out, so this is ready to go too.

I wonder if we really need to add features like the callable arg if there are only 2 plugins that will use it. But I do like the idea of passing it a function that will return the args dynamically, instead of having to override methods. But that's for 4.4 then.

**Pull request merged**
